[APIkeys]
rawgio_key = ""

[Database]
connection_string = "DRIVER={ODBC Driver 17 for SQL Server};SERVER=918121\\SQLEXPRESS;DATABASE=GDW;Trusted_Connection=yes;"

[JSONarchive]
developer_extract = "json_archive\\developer_extract.json"
developer_filtered = "json_archive\\developer_filtered.json"
games_extract = "json_archive\\games_extract.json"
games_filtered = "json_archive\\games_filtered.json"
genre_extract = "json_archive\\genre_extract.json"
genre_properties_filtered = "json_archive\\genre_properties_filtered.json"
genre_bridge_filtered = "json_archive\\genre_bridge_filtered.json"
platform_extract = "json_archive\\platform_extract.json"
platform_properties_filtered = "json_archive\\platform_properties_filtered.json"
platform_bridge_filtered = "json_archive\\platform_bridge_filtered.json"
stores_extract = "json_archive\\stores_extract.json"
stores_properties_filtered = "json_archive\\stores_properties_filtered.json"
stores_bridge_filtered = "json_archive\\stores_bridge_filtered.json"
